### PR TITLE
Ai work/testing

### PR DESCRIPTION
**Pull request by Joshua-Pedersen**
Ai will place checks, take pieces, changed the CLI to have Two player and a Vs Ai mode.

### CODE REVIEW

**Comment by KGB33** [comment]
It is looking good so far. There are a few changes that I think will make it even better. 

# 1 - Separation of concerns

Right now you added a lot of AI-specific code to the `core` piece classes. I think a better approach would be to subclass each piece inside the `ai` package (or create a new class hierarchy, if you can separate them that much).

# 2 - CI failing (locally)
  - Tests failing - I'd be happy to fix them, just let me know.  
    - [`CLITest.testFoolsMate()`](https://github.com/KGB33/EWU-CSCD212-Final-Group-Project/blob/63d03cdb12431d6015bc70801feeb8ffdeae022a/app/src/test/java/cli/CLITest.java#L17) Move input from the test causes the New game type menu to break.
    - [`PawnTest.testEnPassant()`](https://github.com/KGB33/EWU-CSCD212-Final-Group-Project/blob/63d03cdb12431d6015bc70801feeb8ffdeae022a/app/src/test/java/core/classes/PawnTest.java#L41) It looks like this one is caused by [`Board.move()`](https://github.com/KGB33/EWU-CSCD212-Final-Group-Project/blob/63d03cdb12431d6015bc70801feeb8ffdeae022a/app/src/main/java/core/classes/Board.java#L153) missing some logic that is present on `main`. 
  - Formatting issues (`./gradlew.bat goJF`)
  - Unused imports (the formatter will remove them.)

Don't forget `./gradlew.bat ci` will allow you to run the CI locally for faster feedback.

**Comment by Joshua-Pedersen** [comment]
The gradle runtime is on 55.0 while my runtime is on 52.0 so it's having a fit. If you are able to run the formatter on there that'd be awesome.

**Comment by KGB33** [comment]
I noticed that each piece overrides & implements the following methods in the same way:
  - `getScore`
  - `getCurrent`
  - `setCurrent`

These should be implemented in `BasePeice` so they're not re-implemented five times. A good rule of thumb is that you only use `@Override` when the child class's method needs to be implemented differently from the parent object's. 

Furthermore, because these methods are unique to the AI, they should be implemented in sub-classes defined in the `ai` package. You can create interfaces that enforce these methods, then sub-class each piece. 

The `BasePeice.canCheck` method and calls to `setCurrent` in `core.Board` method should also be in the `ai` package for the same reason. 

```java
package ai;

public interface Score {
  int score;
  int getScore();
}
```
```java
package ai;

public interface CurrentSquare {
  char[] current;
  void setCurrent(char[] input);
  char[] getCurrent;
}
```
```java
package ai;

import core.classes.King;

class AiKing extends King implements Score, CurrentSquare {
   ...
}
```


I understand that we are a little crunched on time, if you don't want to refactor into the `AiPeice` style that's fine. However, please at least implement the mentioned methods in `BasePeice` instead of overriding them in each peice.

**Comment by KGB33** [comment]
Looks better. A few things though. 

# 1
Each piece is still re-implementing the `private char[] current;` field.

# 2 
Also, `int getScore()` will always return zero. The score field on `BasePiece` is set to zero, and the child classes re-define the score, but as a `static` variable, but your `BasePeice.getScore()` method returns an instance variable called `score`. Please let me know if you want me to explain this more. 

I added the following test for a pawn, adding additional tests for the other pieces would be a nice bonus.
```java
  @Test
  void testGetScore() {
    final Pawn p = new Pawn(Color.WHITE);
    assertEquals(10, p.getScore());
  }
```

To fix this, remove the score field on the sub-classes, and set it in the constructor. 

# 3 
In the piece constructors you have the following line:
```java
this.current = getCurrent();
```
This line is a no-op. `getCurrent()` returns `this.current`, so you are just setting it to itself.
#  
There is formatting errors too, but I'll take care of them when we are ready to merge.

**Pull request merged**
